//
// ModelError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelError: Codable, Hashable {

    public var message: String?
    public var errors: ErrorErrors?

    public init(message: String? = nil, errors: ErrorErrors? = nil) {
        self.message = message
        self.errors = errors
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case errors
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(errors, forKey: .errors)
    }
}

